### ISSUE TITLE
Unable to tell if a class has a starting weapon

### ISSUE THREAD

**Issue by JayTSmith** [CIS-Extra/mazes_and_minotaurs#22]
As of now, it is impossible to tell if a class has a choice of starting weapons. This could ease the burden of front-end programming if a solution could be found.

**Comment by ThorinSchmidt** [comment]
hmm...  the players handbook has starting equipment listed for each subclass.  some things {like priest robes) are set, while others are a choice (like either 3 javelins, or a bow and 12 arrows) these could be handled with dialog boxes tied to lists...

**Comment by JayTSmith** [comment]
This should be resolved in my latest pull request #24
